Проверка проекта
ArturKrabov/ono-tebe-nado pull request #2
Opened 2024-11-19 07:56 UTC by ArturKrabov

Спасибо что после дедлайна проверили мою работу. Отправляя, думал что просто посмотрите прошел ли я автотесты.

2024-11-19 11:22 UTC, seginel requested changes
Работу вынужден отклонить без потери итерации.

В файле index.html подключён старый файл css, где не исправлены замечания. 
На странице отображаются всё те же расхождения https://disk.yandex.ru/i/WoBP-z4dTUqbvA  https://disk.yandex.ru/i/eqrDYotIZ44OMQ , а в самом CSS строки, которые отмечены как `Надо исправить` - не исправлены.

Однако в файловой структуре я вижу ещё один файл css в корне. Это нарушает пункт из чеклиста: https://disk.yandex.ru/i/Tf18kyFG2Q3HDQ - файлы стилей должны находиться в соответствующей директории.  В проекте не должно быть лишних css-файлов, которые нигде не используются.

2024-11-19 14:05 UTC, ArturKrabov commented
Прошу прощения, неправильно закинул файлы в корень.
Большую часть ошибок исправил, но не могу понять что не так с текстом. Хотя копирую все свойства (font-family, letter-spacing и т.д. из фигмы), но все равно 1 в 1 сделать не получается. Текст в блоке "about" пытался поправить через letter-spacing. letter-spacing у нижнего параграфа отсутствует, а у верхнего - 0.01em (опираясь на фигму)
Я же сделал letter-spacing: 0.0765px и это ближе к макету чем то, что я взял с фигмы, но все равно назвать это идеальным язык не повернется

2024-11-21 13:51 UTC, ArturKrabov commented
Не думал что можно кинуть ссылку еще раз через яндекс-практикум

2024-11-21 18:46 UTC, seginel approved these changes
Спасибо за правки. Вы внесли исправления по всем замечаниям и хочу поздравить - Вы отлично справились с выполнением проектной работы. Отметил в коде и ниже в комментарии оставшиеся замечания. В остальном по странице у меня нет замечаний: страница соответствует макету и требованиям чеклиста.
Работу принимаю. Удачи в дальнейшем обучении.

Из оставшихся расхождений с макетом: https://disk.yandex.ru/i/i0ZBMY5H78FZbw буллет должен быть только между элементами

2024-11-21 18:46 UTC, seginel commented on index.html
> +          <li class="lots__card-list-item">
Не исправлено 
Количество карточек может быть больше, чем в макете. При добавлении новых карточек они должны переноситься на следующую строку. А чтобы при переносе карточки выглядели красиво, в брифе есть отдельная рекомендация по стилизации: https://disk.yandex.ru/i/47OCKIihOY7Ycg. Сейчас при добавлении карточек они не переходят на следующую строку

2024-11-21 18:46 UTC, seginel commented on styles/style.css
> +  grid-template-rows: 595px;
Не стоит фиксировать высоту блока, где есть текст. 
Параграфы могут быть короткими, их может быть больше или меньше, чем в макете. Отступ до футера должен быть как в макете
https://disk.yandex.ru/i/TIkzLV_xNsTI4Q

2024-11-29 13:11 UTC, merged